"""Run the whole model over the recorded fixtures and render a markdown report.

This is the artifact the E2E suite produces. It is committed at
`__snapshots__/valuation_report.md` and diffed on every run, so any change in
behaviour anywhere between the JSON fixture and the fair value per share shows
up as a reviewable text diff rather than a green checkmark.

Deliberately not a pickle or a JSON blob: the point of the artifact is that a
human can read it and notice that Apple is suddenly worth $400.
"""

from __future__ import annotations

from typing import List, Optional

from dcf.assumptions import seed_inputs
from dcf.data import CompanyData, DataFetchError, build_company_data
from dcf.engine import implied_revenue_growth, run_dcf
from dcf.wacc import DEFAULT_EQUITY_RISK_PREMIUM

from tests.e2e import replay

# Pinned, not fetched. The live 10-year Treasury moves daily and would make
# the snapshot churn for reasons that have nothing to do with our code. This
# was the real rate on the day the fixtures were recorded.
E2E_RISK_FREE = 0.0518


class Row:
    """One ticker's trip through the model, or the error that stopped it."""

    def __init__(self, symbol: str):
        self.symbol = symbol
        self.error: Optional[str] = None
        self.company: Optional[CompanyData] = None
        self.wacc_pct: Optional[float] = None
        self.wacc_derived = False
        self.model_price: Optional[float] = None
        self.gap_pct: Optional[float] = None
        self.tv_share_pct: Optional[float] = None
        self.implied_growth: Optional[float] = None
        self.clamped: set = set()


def evaluate(symbol: str) -> Row:
    row = Row(symbol)
    tk = replay.load(symbol)

    try:
        company = build_company_data(symbol, tk)
    except DataFetchError as e:
        row.error = str(e)
        return row

    row.company = company
    seeded = seed_inputs(company, E2E_RISK_FREE, DEFAULT_EQUITY_RISK_PREMIUM)
    row.wacc_pct = seeded.inputs.wacc * 100
    row.wacc_derived = seeded.wacc is not None
    row.clamped = seeded.clamped

    result = run_dcf(seeded.inputs)
    row.model_price = result.fair_value_per_share
    if result.enterprise_value:
        row.tv_share_pct = result.pv_terminal_value / result.enterprise_value * 100
    if company.current_price:
        row.gap_pct = (
            (result.fair_value_per_share - company.current_price)
            / company.current_price
            * 100
        )
        row.implied_growth = implied_revenue_growth(
            seeded.inputs, company.current_price
        )
    return row


def evaluate_all(symbols: List[str] | None = None) -> List[Row]:
    return [evaluate(s) for s in (symbols or replay.available())]


def _pct(x: Optional[float], digits: int = 1) -> str:
    return "—" if x is None else f"{x:.{digits}f}%"


def _money(x: Optional[float]) -> str:
    return "—" if x is None else f"${x:,.2f}"


def render(rows: List[Row]) -> str:
    out: List[str] = []
    out.append("# Valuation report")
    out.append("")
    out.append(
        "Generated by `pytest tests/e2e`. Every number below comes from replaying "
        "recorded Yahoo Finance responses through the full model — data layer, "
        "CAPM, and the DCF engine — with no slider touched."
    )
    out.append("")
    out.append(
        f"Risk-free rate pinned at {E2E_RISK_FREE * 100:.2f}%, equity risk premium "
        f"at {DEFAULT_EQUITY_RISK_PREMIUM * 100:.2f}%, terminal growth 2.50%, "
        "5-year projection."
    )
    out.append("")
    out.append(
        "To change this file, re-record the fixtures "
        "(`python tests/e2e/record.py`) and regenerate "
        "(`E2E_UPDATE_SNAPSHOT=1 pytest tests/e2e`). Read the diff before "
        "committing it."
    )
    out.append("")

    priced = [r for r in rows if r.error is None]
    failed = [r for r in rows if r.error is not None]

    out.append("## Valued")
    out.append("")
    out.append(
        "| Ticker | Recorded | Beta | WACC | Hist. growth | Market | Model | Gap | TV share | Implied growth |"
    )
    out.append("|---|---|---|---|---|---|---|---|---|---|")
    for r in sorted(priced, key=lambda r: r.company.beta or 0):
        c = r.company
        recorded = replay.load(r.symbol).recorded_at
        beta = "—" if c.beta is None else f"{c.beta:.2f}"
        wacc = _pct(r.wacc_pct, 2) + ("" if r.wacc_derived else " *(default)*")
        hist = _pct(
            None if c.historical_revenue_growth is None
            else c.historical_revenue_growth * 100
        )
        implied = _pct(
            None if r.implied_growth is None else r.implied_growth * 100
        ) if r.implied_growth is not None else "**none found**"
        out.append(
            f"| {r.symbol} | {recorded} | {beta} | {wacc} | {hist} | "
            f"{_money(c.current_price)} | {_money(r.model_price)} | "
            f"{_pct(r.gap_pct)} | {_pct(r.tv_share_pct)} | {implied} |"
        )
    out.append("")

    notes: List[str] = []
    for r in sorted(priced, key=lambda r: r.symbol):
        c = r.company
        if c.is_dcf_inappropriate:
            notes.append(
                f"- **{r.symbol}** is in {c.sector}, where a free-cash-flow DCF "
                "is the wrong tool. The app flags it and values it anyway."
            )
        for field in sorted(r.clamped):
            notes.append(
                f"- **{r.symbol}**: the `{field}` default was clamped to fit its "
                "slider range, so the model is not valuing the company its own "
                "history describes."
            )
        if r.implied_growth is None and c.current_price:
            notes.append(
                f"- **{r.symbol}**: the reverse DCF found no revenue growth rate "
                "in its search range that reproduces the market price, and "
                "returned nothing rather than guessing."
            )
        for w in c.warnings:
            notes.append(f"- **{r.symbol}**: {w}")

    if notes:
        out.append("## Notes")
        out.append("")
        out.extend(notes)
        out.append("")

    if failed:
        out.append("## Not valued")
        out.append("")
        for r in sorted(failed, key=lambda r: r.symbol):
            out.append(f"- **{r.symbol}**: {r.error}")
        out.append("")

    return "\n".join(out)
